languageCode = "cn"
languageName = "Chinese"
weight = 1
title = "AcidWall Studio"

[params]
  displayName = "简体中文"
  isoCode = "cn"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "AcidLogo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "The God Of Flowers."

[author]
  name = "AcidWall Studio"
  image = "AcidWallLogo.png"
  headline = "We are Homo Faber."
  bio = "We are Homo Ludens."
  # links = [
  #   { twitter = "https://twitter.com/username" }
  # ]

